### ISSUE TITLE
Link for GoogleDrive or OneDrive

### ISSUE THREAD

**Issue by qjadud1994** [DUTyimmy/generatePGT#2]
Thank you for sharing your great work, MFNet.

I want to try your code, but I cannot access the BaiduDrive link :(

Could you share the bellow datas using GoogleDrive or OneDrive?

```
# from https://github.com/DUTyimmy/generatePGT
- Checkpoint
link: https://pan.baidu.com/s/1G-YHYsfho-rWwMv6VMFT4g. code: oipw

Maps: CAMs & pseudo labels
link: https://pan.baidu.com/s/1nowIVfeauJs6w_k4waBqOA. code: oipw
```

```
# from https://github.com/DUTyimmy/MFNet
training data
link: https://pan.baidu.com/s/1omTCChQFWwNFhQ79AVD8rg. code: oipw

testing datasets
link: https://pan.baidu.com/s/1PBzDP1Hnf3RIvpARmxn2yA. code: oipw

Saliency maps
link: https://pan.baidu.com/s/1IRTEaEicYaCJ2TYjZV1lZA. code: oipw

Checkpoints
link: https://pan.baidu.com/s/14sLu8BtdthD0e8SPK1CT3w. code: oipw
```

**Comment by DUTyimmy** [comment]
Of course! 

the GoogleDrive link is : https://drive.google.com/drive/folders/1KfhiGWS6aXCWkc1a9I7AXk7HYlXwm6SD?usp=sharing

we will also update this ilnk to the README, thinks for your suggestions!

**Comment by qjadud1994** [comment]
Thanks for sharing your dataset.

It will be of great help.
